In [14]:
a, b = 10, 20
c = a+b
name = "mika ozora"
state = status = "belum menikah"
print("Hello world")
print("a + b = ", c)
print("namaku: ", name)
print("status", state)
print("status", status)

Hello world
a + b =  30
namaku:  mika ozora
status belum menikah
status belum menikah


In [23]:
firstName = "mika"
lastName = "ozora"
age = 20
print(firstName + lastName)
print(f"nama: {firstName}, lastname: {lastName}")
print(format(age, ".2f"))

mikaozora
nama: mika, lastname: ozora
20.00


In [15]:
fruits = ["apel", "pisang", "semangka"]
a,b,c = fruits
print(a)
print(b)
print(c)

apel
pisang
semangka


In [19]:
x = "hebat"

def newFunc():
    print("aku", x)

newFunc()
print("Hello main")

aku hebat
Hello main


In [62]:
# random number
import random

print(random.randrange(1, 100)) # 1 - 100

35


In [66]:
# casting
x = 2.5
gpa = 4.0
print(int(x))
print(str(gpa))

2
4.0


In [69]:
a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.


In [83]:
for x in "semangka":
    print(x)

print(len("mikaozora"))
print("ozora" in "mikaozora")
print("ozora" not in "mikaozora")
str = "hello world"
print(str[:5]) # from start
print(str[6:11]) # from index to goals-1
print(str[6:]) # from index to end
print(str.upper())

s
e
m
a
n
g
k
a
9
True
False
hello
world
world
HELLO WORLD


In [85]:
a = 10
b = 20
if a > b:
    print("a larger")
elif a < b:
    print("b larger")
else:
    print("same")

b larger


In [103]:
# list or array
animal = ["anjing", "kuda", "babi"]
for i in animal:
    print(i)
print("---------")
animal.append("jerapah")
print(animal[3])
animal.insert(3, "dugong")
print(animal[3])
print(animal[4])

newAnimal = ["hiu", "lumba-lumba", "piranha"]
animal.extend(newAnimal)
print(animal)

anjing
kuda
babi
---------
jerapah
dugong
jerapah
['anjing', 'kuda', 'babi', 'dugong', 'jerapah', 'hiu', 'lumba-lumba', 'piranha']


In [99]:
for i in range(10, 1, -2):
    print(i)
print()
for i in range(0, 10):
    print(i)

print()
a = 5
while a:
    print(a)
    a -= 1

10
8
6
4
2

0
1
2
3
4
5
6
7
8
9

5
4
3
2
1


In [107]:
def kalkulator(a,b):
    print("menghitung")
    pertambahan = a+b
    return pertambahan, a*b, a/b, a**b

plus, multi, div, power = kalkulator(2,3)
print(f"plus: {plus}\nmulti: {multi}\ndiv: {div}\npower: {power}")

menghitung
plus: 5
multi: 6
div: 0.6666666666666666
power: 8


In [114]:
# numpy
import numpy as np

listAngka = [1,2,3,4,5,6,7,8,9]

print(listAngka)

array1 = [[1,2], [3,4]]
array2 = [[5,6], [7,8]]

print(array1 + array2)

matrix1 = np.array(array1)
matrix2 = np.array(array2)

print(matrix1 + matrix2)
print(matrix1 * matrix2)
print(np.dot(matrix1, matrix2))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1, 2], [3, 4], [5, 6], [7, 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
